accounts/urls.py
from django.urls import path 
from accounts import views
from django.contrib.auth import views as auth_view


app_name = "accounts"

urlpatterns =  [
    path("signup/", views.signup, name="signup"),
    path("signin/", auth_view.LoginView.as_view(template_name="accounts/signin.html"), name="signin"),
    path("signout/", views.user_manager, name="signout"),
    path("login_list/", views.user_manager, name="user_manager"),
    path("user/info/<int:pk>/", views.user_info, name="user_info"),
    path("user/update/<int:pk>/", views.user_update, name="user_update"),
    path("user/delete/<int:pk>/", views.user_delete, name="user_delete"),
    path("user/active/<int:pk>/", views.user_active, name="user_active"),
    path("target_user/info/", views.target_user, name="target_user"),
]

board/urls.py
from django.urls import path
from board import views


app_name = "board"

urlpatterns = [
    path("", views.board_list, name="board_list"),
    path("my/post/<int:pk>/", views.board_list, name="board_mypost"),
    path("my/like/post/<int:pk>/", views.board_like_list, name="board_like_list"),
    path("my/dislike/post/<int:pk>/", views.board_dislike_list, name="board_dislike_list"),
    path("create/", views.board_create, name="board_create"),
    path("detail/<int:pk>/<str:slug>/", views.board_detail, name="board_detail"),
    path("update/<int:pk>/<str:slug>/", views.board_update, name="board_update"),
    path("delete/<int:pk>/<str:slug>/", views.board_delete, name="board_delete"),
    path("post/likes/", views.board_likes, name="board_likes"),
    path("post/dislikes/", views.board_dis_likes, name="board_dis_likes"),
]

conf/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path("accounts/", include("accounts.urls")),
    path("", include("board.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += [
        path('', include(debug_toolbar.urls)), 
    ]

board/models.py
from django.db import models
from base.models import Base_model
from django.conf import settings
from django.shortcuts import reverse

class Post(Base_model):
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    title = models.CharField(max_length=30)
    content = models.TextField(blank=True)
    image = models.ImageField(upload_to="Photo/%Y-%m-%d")
    slug = models.SlugField(db_index=True, allow_unicode=True)
    like = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name="likes", blank=True)
    dis_like = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name="dis_likes", blank=True)
    hit_count = models.IntegerField(default=0, blank=True)
    display_avilable = models.BooleanField("비공개", blank=True)


    class Meta:
        ordering = ("-created", )
        db_table = "posts"


    def __str__(self):
        return self.title

    
    def get_absolute_url(self):
        return reverse("board:board_detail", args=[self.pk, self.slug])


class Comment(Base_model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name="posts")
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    content = models.CharField(max_length=50)

    class Meta:
        ordering = ("-created", )
        db_table = "comments"

    def __str__(self):
        return str(self.author)+"의 댓글"

board/forms.py
from django import forms
from board.models import Post, Comment

class PostCreate_Form(forms.ModelForm):
    class Meta:
        model = Post
        fields = ("title", "content", "image", "display_avilable")


class Comment_Form(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ("content", )

board/views.py
from django.shortcuts import render, get_object_or_404, redirect
from board.models import Post, Comment
from django.core.paginator import Paginator
from datetime import timezone
from board.forms import PostCreate_Form, Comment_Form
from django.http import HttpResponseForbidden, HttpResponse
from user.models import User
from board.session import Hit_session
import json


def board_list(request, pk=None):
    page = request.GET.get("page", 1)
    post_list = Post.objects.filter(is_deleted=False, display_avilable=False).select_related("author").prefetch_related("like", "dis_like")
    page_count = Paginator(post_list , 8)
    page_obj = page_count.get_page(page)
    
    if request.method == "GET":
        search_input = request.GET.get("search_input")
        if search_input is not None:
            post_list = Post.objects.filter(is_deleted=False, display_avilable=False, title__icontains=search_input).select_related("author").prefetch_related("like", "dis_like")
            page_count = Paginator(post_list, 8)
            page_obj = page_count.get_page(page)

    if pk != None:
        user = get_object_or_404(User, id=pk)
        post_list = Post.objects.filter(is_deleted=False, display_avilable=False, author=user).select_related("author").prefetch_related("like", "dis_like")
        page_count = Paginator(post_list, 5)
        page_obj = page_count.get_page(page)
    return render(request, "board/board_list.html", {"post_list": page_obj})

def board_like_list(request, pk):
    page = request.GET.get("page", 1)
    user = get_object_or_404(User, id=pk)
    post_list = Post.objects.filter(is_deleted=False, display_avilable=False, like=user).select_related("author").prefetch_related("like", "dis_like")
    page_count = Paginator(post_list, 5)
    page_obj = page_count.get_page(page)

    if request.method == "GET":
        search_input = request.GET.get("search_input")
        if search_input is not None:
            post_list = Post.objects.filter(is_deleted=False, display_avilable=False, like=user, title__icontains=search_input).select_related("author").prefetch_related("like", "dis_like")
            page_count = Paginator(post_list, 8)
            page_obj = page_count.get_page(page)

    return render(request, "board/board_list.html", {"post_list": page_obj})


def board_dislike_list(request, pk):
    page = request.GET.get("page", 1)
    user = get_object_or_404(User, id=pk)
    post_list = Post.objects.filter(is_deleted=False, display_avilable=False, dis_like=user).select_related("author").prefetch_related("like", "dis_like")
    page_count = Paginator(post_list, 5)
    page_obj = page_count.get_page(page)

    if request.method == "GET":
        search_input = request.GET.get("search_input")
        if search_input is not None:
            post_list = Post.objects.filter(is_deleted=False, display_avilable=False, dis_like=user, title__icontains=search_input).select_related("author").prefetch_related("like", "dis_like")
            page_count = Paginator(post_list, 8)
            page_obj = page_count.get_page(page)

    return render(request, "board/board_list.html", {"post_list": page_obj})


def board_create(request):
    if request.user.is_deleted == False:
        if request.method == "POST":
            form = PostCreate_Form(request.POST, request.FILES)
            if form.is_valid():
                post = form.save(commit=False)
                post.author = request.user
                post.slug = form.cleaned_data.get("title")
                post.save()
                return redirect(Post.get_absolute_url(post))
        else:
            form = PostCreate_Form()
        return render(request, "board/board_create.html", {"form": form})
    else:
        return HttpResponseForbidden


def board_update(request, pk, slug):
    post = get_object_or_404(Post, id=pk, slug=slug)
    if request.user == post.author:
        if request.method == "POST":
            form = PostCreate_Form(request.POST, request.FILES, instance=post)
            if form.is_valid():
                post = form.save(commit=False)
                post.author = request.user
                post.slug = form.cleaned_data.get("title")
                post.save()
                return redirect(Post.get_absolute_url(post))
        else:
            form = PostCreate_Form(instance=post)
        return render(request, "board/board_create.html", {"form": form})
    else:
        return HttpResponseForbidden()

def board_detail(request, pk, slug):
    post = get_object_or_404(Post, id=pk, slug=slug)
    page = request.GET.get("page", 1)
    post_list = post.posts.all()
    page_count = Paginator(post_list, 5)
    page_obj = page_count.get_page(page)

    a = Hit_session(request)
    a.hit_add(post)

    if request.method =="POST":
        form = Comment_Form(request.POST)
        if form.is_valid():
            data = form.save(commit=False)
            data.author = request.user
            data.post = post
            data.save()
            return redirect(Post.get_absolute_url(post))
    else:
        form = Comment_Form()

    return render(request, "board/board_detail.html", {"post": post, "form": form, "comment_page": page_obj})


def board_delete(request, pk, slug):
    post = get_object_or_404(Post, id=pk, slug=slug)
    if request.user == post.author:
        post.delete()
        return redirect("board:board_list")
    else:
        return HttpResponseForbidden()



def board_likes(request):
    if request.is_ajax():
        post_id = request.GET.get("post_id")
        post = Post.objects.get(id=post_id)
        if not request.user.is_authenticated:
            message = "로그인을 해주세욥"
            context = {"like_count": post.like.count(), "message": message}
            return HttpResponse(json.dumps(context), content_type="application/json")

        if request.user in post.like.all():
            post.like.remove(request.user)
            message = "좋아요를 취소합니다."
        else: 
            post.like.add(request.user)
            message = "좋아요를 눌렀습니다."
        context = {'like_count' : post.like.count(),"message":message}
        return HttpResponse(json.dumps(context), content_type="application/json")


def board_dis_likes(request):
    if request.is_ajax():
        post_id = request.GET.get("post_id")
        post = Post.objects.get(id=post_id)
        if not request.user.is_authenticated:
            message = "로그인을 해주세욥"
            context = {"dis_like_count": post.dis_like.count(), "message": message}
            return HttpResponse(json.dumps(context), content_type="application/json")

        if request.user in post.dis_like.all():
            post.dis_like.remove(request.user)
            message = "싫어요를 취소합니다."
        else: 
            post.dis_like.add(request.user)
            message = "싫어요를 눌렀습니다."
        context = {'dis_like_count' : post.dis_like.count(),"message":message}
        return HttpResponse(json.dumps(context), content_type="application/json")               

board/templates/board/board_create.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block title %} 글 작성 페이지 {% endblock %}

{% block content %}
<form action="" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {% load bootstrap4 %}
    {% bootstrap_form form %}
    <input class="btn btn-info" type="submit" value="글 등록">
</form>
{% endblock %}

board/templates/board/board_detail.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block title %} 상세페이지 {% endblock %}

{% block content %}
<br>
<div class="row">
    <div class="col-md-1"></div>
    <div class="col-md-6">

        <div class="card">
            <div class="card-body">
                <p class="text-center">{{post.title}}</p><hr>
                <p>
                    <h6 class="badge badge-secondary">작성자 : {{post.author}}</h6> 
                    <h6 class="badge badge-secondary">작성일 : {{post.created|date:'Y-m-d H:i:s'}}</h6> 
                    <h6 class="badge badge-secondary">조회수 : {{post.hit_count}}</h6>
                </p>
                {% if post.image %}
                <p class="text-center"><img src="{{ post.image.url }}" width="70%"></p>
                {% endif %}
                <p class="text-center">{{ post.content }}</p>
                
                <p class="text-center">
                    <button id="{{ post.id }}" onclick="click_post_like(this.id)" type="submit" class="btn btn-primary">좋아요 
                        <span id="like_count"  class="badge bg-secondary">{{post.like.all|length}}</span>
                    </button>
                        
                    <button id="{{ post.id }}" onclick="click_post_dis_like(this.id)" type="submit" class="btn btn-danger">싫어요 
                        <span id="dis_like_count" class="badge bg-secondary">{{post.dis_like.all|length}}</span>
                    </button>
                </p>
                <div>
                    <div class="text-center" id="message"></div>
                </div>   
                {% if post.author == request.user %}
                    <a class="btn btn-info" href="{% url 'board:board_update' post.pk post.slug %}">수정</a>
                    <a class="btn btn-warning" href="{% url 'board:board_delete' post.pk post.slug %}">삭제</a>
                {% endif %}
            </div>
            <br><br><br>
        </div>
    </div>
    <div class="col-md-5">
        <p class="alert alert-success text-center">간단한 한줄 리뷰</p>
        {% for comment in comment_page %}
        <div class="form-group mt-1">
            <small class="badge badge-info">{{ comment.content }}</small><br>
            <small><strong>작성자 : {{ comment.author.nick_name }}</strong></small>
            <small>({{comment.created|timesince}}), 전 작성됨</small>
        </div>
        {% endfor %}

        {% bootstrap_pagination comment_page %}
        <div class="form-group">    
            <form action="" method="POST">
                {% csrf_token %}
                <label>댓글 남기기</label>
                {% if not user.is_authenticated %}
                    <textarea name="content" class="form-control" rows="2">{% if not user.is_authenticated %} 로그인을 해주세요 {% endif %}</textarea>
                {% else %}
                    <textarea name="content" class="form-control" rows="2"></textarea>
                    <input class="btn btn-primary mt-2" type="submit" value="제출">
                {% endif %}
            </form>
        </div>
    </div>
</div>

 


{% endblock %}

{% block js %}
<script>
    function click_post_like(post_id) {
        $.ajax({
            url: "{% url 'board:board_likes' %}",
            data: {
                'post_id': post_id
            },
            dataType: "json",
            success: function (response) {
                $('#like_count').html(response.like_count)
                $('#message').html(response.message)
            }
        })
    }
</script>

<script>
    function click_post_dis_like(post_id) {
        $.ajax({
            url: "{% url 'board:board_dis_likes' %}",
            data: {
                'post_id': post_id
            },
            dataType: "json",
            success: function (response) {
                $('#dis_like_count').html(response.dis_like_count)
                $('#message').html(response.message)
            }
        })
    }
</script>
{% endblock %}

board/templates/board/board_list.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block title %} 게시판 리스트 {% endblock %}

{% block content %}
{% if request.GET.search_input %}
<p class="alert alert-danger text-center">'{{ reuqest }} {{ request.GET.search_input }}' 에 대한 검색결과 입니다.</p>
{% endif %}

<table class="table table-hover">
    <thead>
        <tr>
            <th>번호</th>
            <th>제목</th>
            <th>작성자</th>
            <th>날짜</th>
            <th>조회수</th>
            <th>좋아요</th>
            <th>싫어요</th>
        </tr>
    </thead>
    <tbody>
        {% for post in post_list %}
        <tr>
            <td>{{post.id}}</td>
            <td><a href="{{ post.get_absolute_url }}">{{post.title}}  {% if post.posts.all|length > 0 %}<span class="badge bg-warning rounded-pill text-dark">{{ post.posts.all|length }}</span>{% endif %}</a></td>
            <td><h6><a href="{% url 'accounts:user_info' post.author.pk %}" class="badge bg-secondary text-white">{{post.author.nick_name}}</a></h6></td>
            <td>{{post.created|date:'Y-m-d H:i:s'}}</td>
            <td>{{post.hit_count}}</td>
            <td>{{post.like.all|length}}</td>
            <td>{{post.dis_like.all|length}}</td>
        </tr>
    </tbody>
        {% endfor %}
</table>

{% bootstrap_pagination post_list %}
{% if user.is_authenticated %}
<a class="btn btn-info border" href="{% url 'board:board_create' %}">글 쓰기</a>
{% endif %}
{% endblock %}