accounts/urls.py
from django.urls import path 
from accounts import views
from django.contrib.auth import views as auth_view


app_name = "accounts"

urlpatterns =  [
    path("signup/", views.signup, name="signup"),
    path("signin/", auth_view.LoginView.as_view(template_name="accounts/signin.html"), name="signin"),
    path("signout/", views.user_manager, name="signout"),
    path("login_list/", views.user_manager, name="user_manager"),
    path("user/info/<int:pk>/", views.user_info, name="user_info"),
    path("user/update/<int:pk>/", views.user_update, name="user_update"),
    path("user/delete/<int:pk>/", views.user_delete, name="user_delete"),
    path("user/active/<int:pk>/", views.user_active, name="user_active"),
    path("target_user/info/", views.target_user, name="target_user"),
]

conf/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path("accounts/", include("accounts.urls")),
    path("", include("board.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += [
        path('', include(debug_toolbar.urls)), 
    ]

accounts/models.py
from django.db import models

# Create your models here.

accounts/forms.py
from django import forms
from user.models import User


class UserForm(forms.ModelForm):
    password = forms.CharField(label="패스워드", widget=forms.PasswordInput)
    password2 = forms.CharField(label="패스워드 확인", widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ("nick_name", "username", "password", "password2")
        labels= {
            "nick_name": "닉네임",
            "username": "아이디",
            }
    
    def clean_nick_name(self):
        check = self.cleaned_data.get("nick_name")
        if User.objects.filter(nick_name=check):
            raise forms.ValidationError("이미 존재하는 닉네임 입니다.")
        return check

    def clean_password2(self):
        check = self.cleaned_data
        if check.get("password") != check.get("password2"):
            raise forms.ValidationError("패스워드가 일치하지 않아요")
        return check

class UserUpdateForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ("nick_name", ) 
        labels = {"nick_name": "변경할 닉네임"}

    def clean_nick_name(self):
        check = self.cleaned_data.get("nick_name")
        if User.objects.filter(nick_name=check):
            raise forms.ValidationError("이미 존재하는 닉네임 입니다.")
        return check
        

accounts/views.py
from django.shortcuts import render, redirect, get_object_or_404
from accounts.forms import UserForm, UserUpdateForm
from user.models import User
from django.contrib.auth import login, logout, authenticate
from django.http import HttpResponse, HttpResponseForbidden
from rest_framework.decorators import api_view
from rest_framework.response import Response
from accounts.serializer import Accounts_Serializer
from board.models import Post, Comment

# Create your views here.
def signup(request):
    if request.method == "POST":
        form = UserForm(request.POST)
        if form.is_valid():
            del(form.cleaned_data["password2"])
            User.objects.create_user(**form.cleaned_data)
            return redirect("board:board_list")
    else:
        form = UserForm()
    return render(request, "accounts/signup.html", {"form": form})

    

@api_view(["GET", "POST"])
def user_manager(request):
    if request.method == "GET":     # 로그아웃 
        logout(request)
        return redirect("board:board_list")

    if request.method == "POST":    # 로그인
        users = authenticate(
            username=request.POST.get("username"),
            password=request.POST.get("password"))
        if users:
            login(request, users)
            return redirect("board:board_list")
        else:
            return HttpResponse('로그인 실패. 다시 시도 해보세요.')


def user_info(request, pk):
    users = get_object_or_404(User, id=pk)
    post = Post.objects.filter(author=users)
    comment = Comment.objects.filter(author=users)

    return render(request, "accounts/user_info.html", {"users": users, "post": post, "comment": comment}) 


def user_update(request, pk):
    if request.user.id == pk:
        users = get_object_or_404(User, id=pk)
        if request.method == "POST":
            form = UserUpdateForm(request.POST, instance=users)
            if form.is_valid():
                form.save()
                return redirect("accounts:user_info", request.user.pk)
        else:
            form = UserUpdateForm(instance=users)
        return render(request, "accounts/user_update.html", {"form":form})
    else:
        return HttpResponseForbidden()

def user_delete(request, pk):
    if request.user.id == pk:
        users = get_object_or_404(User, id=pk)
        if request.method == "POST":
            check = request.POST.get("delete_input")
            if check != "탈퇴하기":
                return HttpResponse("잘못된 타이핑입니다")
            users.delete()
            return redirect("accounts:user_info", request.user.pk)
        return render(request, "accounts/user_delete.html", {"users": users})
    else:
        return HttpResponseForbidden()

def user_active(request, pk):
    if request.user.id == pk:
        users = get_object_or_404(User, id=pk)
        users.is_deleted = False
        users.deleted = None
        users.save()
        return redirect("board:board_list")
    else:
        return HttpResponseForbidden()

def target_user(request):
    if request.method == "GET":
        target_user = User.objects.filter(nick_name=request.GET.get("search_user"))
        if target_user:
            return render(request, "accounts/target_user.html", {"target_user": target_user[0]})
        else:
            return redirect("accounts:user_info", request.user.pk)
        

accounts/templates/accounts/signin.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block title %} 로그인 페이지 {% endblock %}

{% block content %}
<form action="{% url 'accounts:user_manager' %}" method="POST">
    {% csrf_token %}
    {% load bootstrap4 %}
    {% bootstrap_form form %}
    <input class="btn btn-info" type="submit" value="로그인">
</form>
{% endblock %}

accounts/templates/accounts/signup.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block title %} 회원가입 페이지 {% endblock %}

{% block content %}
<form action="" method="POST">
    {% csrf_token %}
    {% load bootstrap4 %}
    {% bootstrap_form form %}
    <input class="btn btn-info" type="submit" value="회원가입">
</form>
{% endblock %}

accounts/templates/accounts/target_user.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block title %} 서치유저 페이지 {% endblock %}

{% block content %}

  
<br><br><br><br>
<div class="row">
    
    <div class="col-md-3"></div>
    <div class="col-md-6 text-center">
        <table>
            <form class="d-flex" action="{% url 'accounts:target_user' %}" method="GET">
                <input  name="search_user" placeholder="유저 닉네임 검색" value="{{ request.GET.user_search }}">
                <input  type="submit" value="Search">
            </form><hr>
        닉네임 : {{ target_user.nick_name }} <hr>
        아이디 : {{ target_user.username }} <hr>
        생성한지 : {{ target_user.created|timesince }}, 전 <hr>
        계정상태 : <strong>{% if users.is_deleted == True %} 사용불가 (탈퇴 진행중) {% else %} 사용가능 {% endif %}</strong> <hr>
        탈퇴요청날짜 : {{ target_user.deleted }} <hr>
    </table>
    </div>
    <div class="col-md-3"></div>
</div>
{% endblock %}

accounts/templates/accounts/user_delete.html
{% extends 'base.html' %}
{% block title %} 회원탈퇴 페이지 {% endblock %}

{% block content %}

<!-- Button trigger modal -->
<button type="button" class="btn btn-danger" data-bs-toggle="modal" data-bs-target="#staticBackdrop">
    회원탈퇴
  </button>
  
  <!-- Modal -->
  <div class="modal fade" id="staticBackdrop" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="staticBackdropLabel">Warning ! </h5>
          <button type="button" class="btn-close btn btn-warning btn-sm" data-bs-dismiss="modal" aria-label="Close">취소</button>
        </div>
        <div class="modal-body">
          <p class="alert alert-danger">{{ user }}, 회원님 정말 회원탈퇴를 진행하실건가요?</p> 
          <p class="alert alert-danger"> 탈퇴를 원하시는 경우엔 <strong>"탈퇴하기"</strong>를 입력해주세요</p>


        </div>
        <div class="modal-footer">
          <form action="" method="POST">
              {% csrf_token %}
              <input type="text" name="delete_input">
              <input class="btn btn-primary btn-sm" type="submit" value="확인"> 
          </form>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

accounts/templates/accounts/user_info.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block title %} 유저정보 페이지 {% endblock %}

{% block content %}

  
<br><br><br><br>
<div class="row">
    
    <div class="col-md-3">
        <div class="card">
            <div class="card-body">
                <h7>작성한 글 : {{ post|length }}개</h7> <hr>
                <h7>작성한 댓글 : {{ comment|length }}개</h7> <hr>
                <h7>좋아요 받고 누른횟수 : {{ user.likes.all|length }}</h7> <hr>
                <h7>싫어요 받고 누른횟수 : {{ user.dis_likes.all|length }}</h7> <hr>
            </div>
        </div>
    </div>
    <div class="col-md-6 text-center">
        <table>
            <form class="d-flex" action="{% url 'accounts:target_user' %}" method="GET">
                <input  name="search_user" placeholder="유저 닉네임 검색" value="{{ request.GET.search_user }}">
                <input  type="submit" value="Search">
            </form><hr>
        닉네임 : {{ users.nick_name }} <hr>
        아이디 : {{ users.username }} <hr>
        생성한지 : {{ users.created|timesince }}, 전 <hr>
        계정상태 : <strong>{% if users.is_deleted == True %} 사용불가 (탈퇴 진행중) {% else %} 사용가능 {% endif %}</strong> <hr>
        탈퇴요청날짜 : {{ user.deleted|date:'Y-m-d / H:i:s' }} <hr>
    </table>
    {% if request.user == users %}

    <a class="btn btn-info" href="{% url 'accounts:user_update' users.pk %}">회원정보 수정</a>
        {% if users.is_deleted == False %}
            <a class="btn btn-danger" href="{% url 'accounts:user_delete' users.pk %}">계정탈퇴 요청</a>
        {% else %}
        <a class="btn btn-danger" href="{% url 'accounts:user_active' users.pk %}">계정복구</a>
        {% endif %}

    {% endif %}
    </div>
    <div class="col-md-3"></div>
</div>
{% endblock %}

accounts/templates/accounts/user_update.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block title %} 회원정보 수정 페이지 {% endblock %}

{% block content %}
<form action="" method="POST">
    {% csrf_token %}
    {% load bootstrap4 %}
    {% bootstrap_form form %}
    <input class="btn btn-info" type="submit" value="수정하기">
</form>
{% endblock %}