accounts/urls.py
from django.urls import path 
from accounts import views
from django.contrib.auth import views as auth_view


app_name = "accounts"

urlpatterns =  [
    path("signup/", views.signup, name="signup"),
    path("signin/", auth_view.LoginView.as_view(template_name="accounts/signin.html"), name="signin"),
    path("signout/", views.user_manager, name="signout"),
    path("login_list/", views.user_manager, name="user_manager"),
    path("user/info/<int:pk>/", views.user_info, name="user_info"),
    path("user/update/<int:pk>/", views.user_update, name="user_update"),
    path("user/delete/<int:pk>/", views.user_delete, name="user_delete"),
    path("user/active/<int:pk>/", views.user_active, name="user_active"),
    path("target_user/info/", views.target_user, name="target_user"),
]

board/urls.py
from django.urls import path
from board import views


app_name = "board"

urlpatterns = [
    path("", views.board_list, name="board_list"),
    path("my/post/<int:pk>/", views.board_list, name="board_mypost"),
    path("my/like/post/<int:pk>/", views.board_like_list, name="board_like_list"),
    path("my/dislike/post/<int:pk>/", views.board_dislike_list, name="board_dislike_list"),
    path("create/", views.board_create, name="board_create"),
    path("detail/<int:pk>/<str:slug>/", views.board_detail, name="board_detail"),
    path("update/<int:pk>/<str:slug>/", views.board_update, name="board_update"),
    path("delete/<int:pk>/<str:slug>/", views.board_delete, name="board_delete"),
    path("post/likes/", views.board_likes, name="board_likes"),
    path("post/dislikes/", views.board_dis_likes, name="board_dis_likes"),
]

conf/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path("accounts/", include("accounts.urls")),
    path("", include("board.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += [
        path('', include(debug_toolbar.urls)), 
    ]

base/models.py
from django.db import models
from datetime import datetime


class Base_model(models.Model):
    is_deleted = models.BooleanField(default=False, blank=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    deleted = models.DateTimeField(null=True, blank=True)

    class Meta:
        abstract = True

    def delete(self, using=None, Keep_parents=False):
        self.is_deleted = True
        self.deleted = datetime.now()
        self.save()

base/views.py
from django.shortcuts import render

# Create your views here.

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <title>{% block title %} {% endblock %}</title>
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
</head>
<body>
{% include 'navbar.html' %}
{% block content %}    

{% endblock %}
{% include 'footer.html'%}

<script src="https://code.jquery.com/jquery-3.5.1.min.js" integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0=" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.4/dist/umd/popper.min.js" integrity="sha384-q2kxQ16AaE6UbzuKqyBE9/u/KzioAlnx2maXQHiDX9d4/zp8Ok3f+M7DPm+Ib6IU" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.min.js" integrity="sha384-pQQkAEnwaBkjpqZ8RU1fF1AKtTcHJwFl3pblpTlHXybJjHpMYo79HY3hIi4NKxyj" crossorigin="anonymous"></script>

{% block js %}

{% endblock %}

</body>
</html>

templates/footer.html
<nav class="navbar fixed-bottom navbar-expand-sm navbar-dark bg-dark">
        <p class="text-white text-center"></p>
</nav>

templates/navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container-fluid">
      <a class="navbar-brand" href="{% url 'board:board_list' %}">포토게시판 광장</a>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        
        <form class="d-flex" method="GET">
          <input class="form-control me-2" name="search_input" placeholder="Search" value="{{ request.GET.search_input }}">
          <h1 style="padding-left: 5px;"></h1>
          <input class="btn btn-outline-success" type="submit" value="Search">
        </form>
        {% if user.is_authenticated %}
          <h1 style="padding-left: 15px;"></h1>
          <a class="btn btn-secondary btn-sm"href="{% url 'board:board_mypost' user.pk %}">내가 작성한 글</a>
          <h1 style="padding-left: 10px;"></h1>
          <a class="btn btn-success btn-sm"href="{% url 'board:board_like_list' user.pk %}">내가 좋아하는 글</a>
          <h1 style="padding-left: 10px;"></h1>
          <a class="btn btn-danger btn-sm"href="{% url 'board:board_dislike_list' user.pk %}">내가 싫어하는 글</a>
        {% endif %}
    </div>
    
    {% if user.is_authenticated %}
    <ul class="navbar-nav">
      <li class="nav-item">
        <a class="nav-link text-dark border">{{ user.nick_name }} 접속중…</a>
      </li>
      <li class="nav-item">
        <a class="nav-link text-dark border" href="{% url 'accounts:signout' %}">로그아웃</a>
      </li>
      <li class="nav-item">
        <a class="nav-link text-dark border" href="{% url 'accounts:user_info' user.pk %}">내 정보</a>
      </li>
    </ul>
    {% else %}
    <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link text-dark border" href="{% url 'accounts:signin' %}">로그인</a>
        </li>
        
        <li class="nav-item">
            <a class="nav-link text-dark border" href="{% url 'accounts:signup' %}">회원가입</a>
          </li>
      </ul>
    {% endif %}
  </nav>